### ISSUE TITLE
how to use wav files to float array 

### ISSUE THREAD

**Issue by ahmedlone127** [Sciss/AudioFile#6]
Hey i am trying to a wav file to an array of floats but i can't find how  , someone directed me to your repository but I am still having trouble would be lovely if you could point me in the right direction :)

**Comment by Sciss** [comment]
Hi there. Do you mean to _read_ or _write_ a wav file? Both cases are shown in the [README.md](https://github.com/Sciss/AudioFile/blob/main/README.md). So to read, `val in = AudioFile.openRead("input.aif"); val buf: Array[Array[Double]] = in.buffer(8192); in.read(buf); in.close()`. the `buffer` method is just convenience for creating a 2-dimensional buffer of `Double` elements. The number of frames in the file is given by `in.numFrames`, the number of channels by `in.numChannels`. The samples are found via `buf(channel)(offset)`.
